name: Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Fetch Tags
        run: git -c protocol.version=2 fetch --tags --progress --no-recurse-submodules origin
        if: "!contains(github.ref, 'refs/tags')"
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'corretto'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get Release Version
        id: get_version
        run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Upload artifact zip
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: aws-ec2-ice-node-execution-${{ steps.get_version.outputs.VERSION }}
          # Directory containing files to upload
          path: build/libs/aws-ec2-ice-node-execution-${{ steps.get_version.outputs.VERSION }}.zip
